[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Ibrahim Oshinubi <ibrahim.oshinubi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
loguru = "^0.7.3"
dotenv = "^0.9.9"
quixstreams = "3.9.0"
pydantic-settings = "^2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
